kind: pipeline
name: default

steps:
- name: publish
  image: plugins/docker
  settings:
    registry: docker-registry.theautomation.nl
    repo: docker-registry.theautomation.nl/test/lap
    username:
      from_secret: docker-registry-username
    password:
      from_secret: docker-registry-password
    tags:
      - latest