kind: pipeline
name: default

steps:
- name: publish
  image: plugins/docker
  settings:
    registry: docker-registry.theautomation.nl
    repo: docker-registry.theautomation.nl/test/lap
    auto_tag: true
    username:
      from_secret: docker-registry-username
    password:
      from_secret: docker-registry-password

- name: test
  image: compose:1.23.2
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - up -f ./docker-compose.yaml

volumes:
- name: docker
  host:
    path: /var/run/docker.sock