---
kind: pipeline
name: validate

steps:
  - name: lint
    image: sdesbure/yamllint:latest
    commands:
      - yamllint -c ./.yamllint .

  - name: docker-compose
    image: tmaier/docker-compose:latest
    commands:
      - mv prd-node-red-app.env.example prd-node-red-app.env
      - docker-compose config -q

---
kind: pipeline
type: docker
name: build

depends_on:
  - validate

steps:
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker-registry-username
      password:
        from_secret: docker-registry-password
      registry: docker-registry.theautomation.nl
      repo: docker-registry.theautomation.nl/coen/prd-node-red-app
      auto_tag: true

---
kind: pipeline
type: docker
name: upgrade

depends_on:
  - build

steps:
  - name: upgrade
    image: appleboy/drone-ssh
    settings:
      host: docker.stam.lan
      username: coen
      password:
        from_secret: ssh_password
      port: 22
      script:
        - cd /home/coen/docker-home-services/node-red
        - git pull
        - docker-compose pull

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: docker.stam.lan
      username: coen
      password:
        from_secret: ssh_password
      port: 22
      script:
        - cd /home/coen/docker-home-services/node-red
        - docker-compose up -d

  - name: clean
    image: appleboy/drone-ssh
    settings:
      host: docker.stam.lan
      username: coen
      password:
        from_secret: ssh_password
      port: 22
      script:
        - cd /home/coen/docker-home-services/node-red
        - docker image prune -f

---
kind: pipeline
name: notify

depends_on:
  - upgrade

steps:
  - name: notify
    image: drillster/drone-email
    settings:
      from:
        from_secret: email-address
      host: smtp.gmail.com
      username:
        from_secret: email-address
      password:
        from_secret: email-password
      recipients:
        - c.stam.mail@gmail.com
      subject: >
          [{{ build.status }}]
          {{ repo.owner }}/{{ repo.name }}
          ({{ build.branch }} - {{ truncate build.commit 8 }})
      body:
        https://git.io/vgvPz
