kind: pipeline
name: default

steps:
- name: publish
  image: plugins/docker
  settings:
    registry: docker-registry.theautomation.nl
    repo: docker-registry.theautomation.nl/test/lap
    auto_tag: true
    username:
      from_secret: docker-registry-username
    password:
      from_secret: docker-registry-password

- name: deploy
  image: docker
  commands:
  - sh ./docker-compose up -d
  volumes:
  - name: docker
    path: /var/run/docker.sock

volumes:
- name: docker
  host:
    path: /var/run/docker.sock