version: "3.8"
services:

  prd-node-red-app:
    build: .
    image: nodered/prd-node-red:latest
    container_name: prd-node-red-app
    restart: unless-stopped
    env_file: prd-node-red-app.env
    ports:
      - "1880:1880"
    networks:
      home-services:
    volumes:
      - ./data:/data

# NETWORKS
networks:

  home-services:
    driver: bridge
    name: home-services
    ipam:
      config:
        - subnet: 172.20.0.0/16