---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: settings
  namespace: home-automation
spec:
  encryptedData:
    adminAuth_password: AgDrunVqVva0KwWuS0TH4y4PVsBAf7BCQhmEDH4g/ZtVGEcV8raqMNpOJsc2wJcXQDVlGginpPpcoKssCd9P/od9cJ0Zqc9HKbdBsGz6TG33RxAd0y14SWSKwVDW76ebt3vVzVV01BoVAe6CmFxVwWlNvQakYwsEf65GyMV0MX2NPT+uIkUawzoagKfSRVDl91usgAFXfut0XHU09zqPsvVc/lX/BZGK2vkfBlAOlr6krCkFzFc3SluuaDsNDNm+QNOkBr6oDvGp62xZEwp8zlj679SYo9MD8ePuHv6JSRx3Ij2rc5wtBr/zZs5n52NvrCf+1glZDPut2VvcnmnUx6sQ7P6K8ye5foPb6qpjzWUZsW+VSb0poEhF3b/ys18S2oDKpfcyTOFHqiLOgtB0RIG+Ho9UqV0CANAj6HaihhG1V0RmbRXmWnp+1OpjmMa3wjuKscIM9ctlWHZzoUEyIMoHiCQdJXVHG8Kwx0OIunSz5NNsc2/Dv+Qn4JsF83ejrvNIqRJcEwb/hEJYy3wnDDji4amKod0ifSh3GmgrwKRHMAO8wMilOkuFx61enuAumpqUEbAOnlzAmICNgGdBfPbt4WgfdBfp/7ZHcNWmnhRyQ/b2BPmLdXSc5MbUZIjVMDymjBW/MyED0yedjZs7X591dFc5b+0YQCVcG1eaJqd9rysG/hN5mBQ1Nl4SzcuMNMRo2kOstZ23UEEDJUMoXa75NeJzXv+RInjLZdHHL27dVcIY4e1eA3xvr+u6U+wwlNxxt9bJgCHnXGkxwvc=
    httpAuth: AgBEwm9YTjWVlBYAuWXemk/NUZvEmPh1SQinA4pFcmVoKLVxXFvrmSqc1GXtF/oatKZtcrSdPwwbTfFpbC1goaQF1HM18lnhnJcajMkSPmJ/tAZsQDi/XlrH6qasgguPZ0TBWXdX1gS+S7MpP/iAoXMa3gwRRrUHmeqYYg5mC74RM3e/AXXT8gPsTPj+ZzuostyZzHzrGC2AZiEMLhvfj5tOglLj3yfOjAcDlMbIPsfpUSysXwm8eNC/VWr9tso1NSgh7o2ZDO9RYYSvYuWv62T/2oKLLUSF6eqeI4Yznrk3HqUQDXMT4ZBYviKead5chW9WVfm2LxGAh1PPzX48iFN4stvQ9MefteE1gW8pB0p7+suDQgNLblMYF40W+oP94l/YE6Ywd/GNUIjmWz1ue5zU2opNprjpyamek1lWJ4MmooggNnejAuIg9jiPZx2YnI2MokFobp6GIqAQYjr02giqdmQT+LUK6OPCr4AHCPES7H8OPqY0/tYV8pGQ4lKgukUBjWl2JAAQ7HLhyH8E9kaGTK2DijN6NPcYzpSk44vBR1BKijNz+so8yUX4TnVov0VY47fQKMouupqNnAkq4CBxlHx9D57ky+0IDwFK7dX57HCBZPKstN1xGLDGzXDVLrILpWucDD2Q2H38hcsQPIGSxCAl2CtaRcqMDSI+apzOqwDGHoAnNpbnU+lGi+7YTpXxcXl0Nm9EXrocC/WngA+Q4B76XfnIBm1jsk0w9gg/6CYiAfW0XAYfCn5wko2sCbuchNq4wjAjkzv2U8A=
  template:
    data:
      settings.js: |-
        module.exports = {
            flowFile: 'flows.json',
            credentialSecret: "a-secret-key",
            flowFilePretty: true,
            adminAuth: {
            type: "credentials",
            users: [{
                username: "admin",
                password: "{{ index . "adminAuth_password" }}",
                permissions: "*"
            }]
            },
            httpNodeAuth: {user:"nodered-endpoint",pass:"{{ index . "httpAuth" }}"},
            httpStaticAuth: {user:"nodered-endpoint",pass:"{{ index . "httpAuth" }}"},
            uiPort: process.env.PORT || 1880,
            logging: {
                console: {
                    level: "info",
                    metrics: false,
                    audit: false
                }
            },
            exportGlobalContextKeys: false,
            externalModules: {},
            editorTheme: {
                palette: {},
                projects: {
                    enabled: false,
                    workflow: {
                        mode: "manual"
                    }
                },
                codeEditor: {
                    lib: "ace",
                    options: {
                        theme: "vs",
                    }
                }
            },
            functionExternalModules: true,
            functionGlobalContext: {},
            debugMaxLength: 1000,
            mqttReconnectTime: 15000,
            serialReconnectTime: 15000,
        }
    metadata:
      name: settings
      namespace: home-automation
      labels:
        app: node-red

---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: flows-credentials
  namespace: home-automation
spec:
  encryptedData:
    flows-cred: AgAmpvx07H2Vc1arLYGJuMkAjmGegONv289s5B3oeabw2qBx8IFp633JojtWQMSNNzP0f+ZeAT2MoRLU7mKdTt2wpKQZ26mljn91HGVPFZw3HHljWhCduV8Qm1nQZ39FmhfFLWmZ4w9AMzplYfRk7eKT/WiOWAJywlvOqlpb0JhgN3VHZiC5uxT2NdET6YUO/HgRtGkyJuZpBaPdptmGoU/56oKLXaIFAYG9qtazaD9svDpuYjcYvX5sXLZysVg1Uk/aMHoZzEJvtLTrikEdpkojLg1pDo/DZ7hhjPG6WDZEKM3a1O6x3+GMU8L///E+Q2SfaPmp3UAaNzSxhEySDv1wMw9HOBToeIHGf2i0w2KNZQkxp90dppaw/Pq4NaL1DYTx2NUhcFqtOmVw5vO/VncKq2wNj9zEmaIaEGq+P1erHxiWIdjcWkrN+Fi8jE0NJD3xCo1aVKX0c8WOGnszW/+h02czj5SrdI2sZWl9w0ktnEShcQdA2GUpYnIAqneHvVPDVdknYHR0bh+0smjAlFiyURrmcK0cAl1ATJR8HQ9+U+jg3AdGdIcIdZflQvdqxNKjQYFBnQhqkantuGu8mvnxvX8M1eLzezYrgXn+2b3WT1OnDK+YKLtSziC9Feng19ozJ7sGsrgF4TiKcP66jJJSLjZpdlKvIlhpFyYmk5T2EWmzWK6Ig0J8KaBXlioeIdMr347XJLLdOKObfzlcC9hQzHQPG5CNKnVzbkfD9Tkx3SSWu+5pKqGBGKCRZWXFktclV8vP4Q00+CkbsUDYX9AygcIW7AtF7OYkX3wHq4oEzv3Cu8Ym8R1ZVAPIR3IYo87xGS7+oyNlFSXPeoILIa9Vwtledgz3JaOZryFCHbiNV1eZny1dOX0prR8DR9z2kMVrnr87mdryzC524P0FBfBY65npssbH/WW4UeRzAtr5ARdXazjt2Zja6v4bWU3h/x4D9z3P4yRBGAr1u/glzY6k7+nK+71WNaBJ05MWfT7KfjIjeVew+WPe5n5iE2PUwzQ16OHLWQ492EwrZEZ+Y/B2p0uzofne6USLCxcTb7JUZVeMCdf4tnmQ0xLhWtMsVvSeXgqZrrycIHvRLYpYaMzUXywcLnDnhIrk3Jata99M88Yo8tQG2yJbTA00KyNHGr8qOvsKj/4paWQrEXZIuPC29YmD8bt8JM6z5d1/48m3eW+JtbtCWsyFfDJ27aMxGeAyh7+Ea0dzA2Y5UeFAPbeerBnW4VP/BwFRqurOaDNraQ==
  template:
    data:
      flows_cred.json: |-
        {
            "$": "{{ index . "flows-cred" }}"
        }
    metadata:
      labels:
        app: node-red
      name: flows-credentials
      namespace: home-automation

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: node-red
  namespace: home-automation
  labels:
    app: node-red
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-red
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: node-red
    spec:
      containers:
        - name: node-red
          image: "container-image-registry.theautomation.nl/home-automation/node-red:latest@sha256:4166d440a679abb9feaaa924bfd847c58337383be07114f59cdf43c8013ba90f"
          imagePullPolicy: Always
          resources: {}
          ports:
            - containerPort: 1880
              protocol: TCP
          env:
            - name: TZ
              value: Europe/Amsterdam
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
          volumeMounts:
            - name: settings
              mountPath: /data/settings.js
              subPath: settings.js
            - name: flow_cred
              mountPath: /data/flows_cred.json
              subPath: flows_cred.json
      volumes:
        - name: settings
          secret:
            secretName: settings
        - name: flow-cred
          secret:
            secretName: flows-credentials
      imagePullSecrets:
        - name: container-image-registry-credentials

---
kind: Service
apiVersion: v1
metadata:
  name: node-red
  namespace: home-automation
  labels:
    app: node-red
spec:
  selector:
    app: node-red
  type: ClusterIP
  ports:
    - port: 1880
      protocol: TCP
      targetPort: 1880
  sessionAffinity: None

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: node-red
  namespace: home-automation
  labels:
    app: node-red
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  ingressClassName: nginx-private
  rules:
    - host: node-red.k8s.lan
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: node-red
                port:
                  number: 1880
