---
kind: pipeline
type: kubernetes
name: validate

steps:
  - name: yamllint
    image: sdesbure/yamllint:latest
    commands:
      - yamllint -c ./cicd/.yamllint .

---
kind: pipeline
type: kubernetes
name: build

depends_on:
  - validate

steps:
  - name: publish
    image: quay.io/buildah/stable
    privileged: true
    commands:
      - buildah --help
      - buildah bud -f ./deploy/container/main/Containerfile
      - ls -R

---
kind: secret
name: container_image_registry_username
get:
  path: container-image-registry-auth
  name: username

---
kind: secret
name: container_image_registry_password
get:
  path: container-image-registry-auth
  name: password
