---
kind: pipeline
type: kubernetes
name: validate

steps:
  - name: yamllint
    image: sdesbure/yamllint:latest
    commands:
      - yamllint -c ./cicd/.yamllint .

---
kind: pipeline
type: kubernetes
name: build-push

depends_on:
  - validate

steps:
  - name: build
    image: quay.io/buildah/stable
    privileged: true
    environment:
      IMAGE: "container-image-registry.devops.svc:5000/home-automation/home-assistant:latest"
      CONTAINERFILE: "./deploy/container/main/Containerfile"
      STORAGE_DRIVER: "overlay"
      FORMAT: "oci"
      CONTEXT: "."
      TLSVERIFY: "false"
    commands:
      - buildah --storage-driver=$${STORAGE_DRIVER} bud --format=$${FORMAT} --tls-verify=$${TLSVERIFY} --no-cache -f $${CONTAINERFILE} -t $${IMAGE} $${CONTEXT}
      - ls -R

---
kind: secret
name: container_image_registry_username
get:
  path: container-image-registry-auth
  name: username

---
kind: secret
name: container_image_registry_password
get:
  path: container-image-registry-auth
  name: password
