---
kind: pipeline
type: kubernetes
name: validate

steps:
  - name: yamllint
    image: sdesbure/yamllint:latest
    commands:
      - yamllint -c ./cicd/.yamllint .

---
kind: pipeline
type: kubernetes
name: build

depends_on:
  - validate

steps:
  - name: publish
    image: quay.io/buildah/stable:v1.23.3
    environment:
      STORAGE_DRIVER: overlay
    commands:
      - buildah --help
      - echo $(STORAGE_DRIVER)
