---
kind: pipeline
type: kubernetes
name: validate

steps:
  - name: yamllint
    image: sdesbure/yamllint:latest
    commands:
      - yamllint -c ./cicd/.yamllint .

---
kind: pipeline
type: kubernetes
name: publish

depends_on:
  - validate

steps:
  - name: build-push
    image: quay.io/buildah/stable
    privileged: true
    environment:
      REGISTRY_HOST: "container-image-registry.devops.svc:5000"
      IMAGE: "container-image-registry.devops.svc:5000/home-assistant:latest"
      CONTAINERFILE: "./deploy/container/main/Containerfile"
      STORAGE_DRIVER: "overlay"
      FORMAT: "oci"
      CONTEXT: "."
      TLSVERIFY: "false"
      USERNAME:
        from_secret: container_image_registry_username
      PASSWORD:
        from_secret: container_image_registry_password
    commands:
      - echo $${DRONE_BUILD_NUMBER}
      - echo $${DRONE_REPO_NAME}
      - buildah --storage-driver=$${STORAGE_DRIVER} bud --format=$${FORMAT} --tls-verify=$${TLSVERIFY} --no-cache -f $${CONTAINERFILE} -t $${REGISTRY_HOST}/$${DRONE_REPO_NAME}:latest -t $${REGISTRY_HOST}/$${DRONE_REPO_NAME}:$${DRONE_BUILD_NUMBER} $${CONTEXT}
      - buildah push --creds=$${USERNAME}:$${PASSWORD} --tls-verify=$${TLSVERIFY} --digestfile=/tmp/image-digest $${IMAGE} docker://$${IMAGE}
      - cat /tmp/image-digest

---
kind: secret
name: container_image_registry_username
get:
  path: container-image-registry-auth
  name: username

---
kind: secret
name: container_image_registry_password
get:
  path: container-image-registry-auth
  name: password
