---
kind: pipeline
type: kubernetes
name: validate

steps:
  - name: yamllint
    image: sdesbure/yamllint:latest
    commands:
      - yamllint -c ./cicd/.yamllint .

---
kind: pipeline
type: kubernetes
name: build

depends_on:
  - validate

steps:
  - name: publish
    image: plugins/buildah
    settings:
      dry-run: true
      dockerfile: ./deploy/container/Containerfile
      context: .
      tags: buildahoutput
      repo: docker.io/harness/ci-automation
      registry: docker.io
      username:
        from_secret: container_image_registry_username
      password:
        from_secret: container_image_registry_password
      layers: true

---
kind: secret
name: container_image_registry_username
get:
  path: container-image-registry-auth
  name: username

---
kind: secret
name: container_image_registry_password
get:
  path: container-image-registry-auth
  name: password
