---
kind: pipeline
type: kubernetes
name: validate

steps:
  - name: yamllint
    image: sdesbure/yamllint:latest
    commands:
      - yamllint -c ./cicd/.yamllint .

---
kind: pipeline
type: kubernetes
name: publish

depends_on:
  - validate

steps:
  # - name: build-push
  #   image: quay.io/buildah/stable
  #   privileged: true
  #   environment:
  #     IMAGE: "container-image-registry.devops.svc:5000/home-automation/home-assistant:latest"
  #     CONTAINERFILE: "./deploy/container/main/Containerfile"
  #     STORAGE_DRIVER: "overlay"
  #     FORMAT: "oci"
  #     CONTEXT: "."
  #     TLSVERIFY: "false"
  #     USERNAME:
  #       from_secret: container_image_registry_username
  #     PASSWORD:
  #       from_secret: container_image_registry_password
  #   commands:
  #     - echo $${USERNAME} >> test.txt
  #     - echo ${PASSWORD} >> test.txt
  #     - echo 'hallo' >> test.txt
  #     - cat ./test.txt
  #     - buildah --storage-driver=$${STORAGE_DRIVER} bud --format=$${FORMAT} --tls-verify=$${TLSVERIFY} --no-cache -f $${CONTAINERFILE} -t $${IMAGE} $${CONTEXT}
  #     - buildah push --tls-verify=$${TLSVERIFY} --digestfile=/tmp/image-digest $${IMAGE} docker://$${IMAGE}
  #     - cat /tmp/image-digest

  - name: build
    image: alpine
    environment:
      USERNAME:
        from_secret: username
      PASSWORD:
        from_secret: password
    commands:
      - echo $${USERNAME} >> test.txt
      - echo $${PASSWORD} >> test.txt
      - echo 'hallo' >> test.txt
      - cat ./test.txt

---
kind: secret
name: username
get:
  path: container-image-registry-auth
  name: username

---
kind: secret
name: password
get:
  path: container-image-registry-auth
  name: password
