kind: pipeline
type: docker
name: default

steps:
- name: publish
  image: plugins/docker
  settings:
    registry: docker-registry.theautomation.nl
    repo: docker-registry.theautomation.nl/coen/prd-node-red
    auto_tag: true
    username:
      from_secret: docker-registry-username
    password:
      from_secret: docker-registry-password

- name: test
  image: docker
  commands:
  - sh ./.drone/deploy.sh
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock