kind: pipeline
type: docker
name: default

steps:
- name: publish
  image: plugins/docker
  settings:
    registry: docker-registry.theautomation.nl
    repo: docker-registry.theautomation.nl/coen/prd-node-red
    auto_tag: true
    username:
      from_secret: docker-registry-username
    password:
      from_secret: docker-registry-password

- name: build
  image: docker
  environment:
    USERNAME:
      from_secret: docker-registry-username
    PASSWORD:
      from_secret: docker-registry-password
  commands:
  - docker login -u $USERNAME -p $PASSWORD https://docker-registry.theautomation.nl
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock
