kind: pipeline
type: docker
name: default

steps:

- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker-registry-username
    password:
      from_secret: docker-registry-password
    registry: docker-registry.theautomation.nl
    repo: docker-registry.theautomation.nl/coen/prd-node-red
    auto_tag: true

- name: build
  image: docker
  environment:
    docker-registry-username:
      from_secret: docker-registry-username
    docker-registry-password:
      from_secret: docker-registry-password
  commands:
  - docker login -u $docker-registry-username -p $docker-registry-password https://docker-registry.theautomation.nl
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock
